-- Active: 1662659335013@@35.226.146.116@3306@freire-aline-chagas
### 
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "cliente1",
    "adress":"casa da mãe joanvvvva",
    "phone":11123456789,
    "email": "cliente1@gmail.com",
    "birth_date":"1990-01-01",
    "login":"cliente1",
    "password": "qwertyuiop",
    "profile_pic":"bananinha"
}

###
# @name login
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "login": "cliente1",
    "password": "qwertyuiop"
}

###
DELETE http://localhost:3003/users/delete
Authorization: {{login.response.body.token}}
Content-Type: application/json

{
    "login": "cliente1",
    "password": "qwertyuiop",
    "email":"cliente1@gmail.com"
}

###
POST http://localhost:3003/products/insert-product
Content-Type: application/json

{
    "name":"bola",
    "price":"5",
    "brand":"futebola",
    "product_tax":"8",
    "quantity":"100",
    "product_image":"imagem de bola",
    "description":"bola. excelente pra chutar na janela do vizinho",
    "value":"5,00"
        
}
