-- Active: 1662659335013@@35.226.146.116@3306@freire-aline-chagas
### 
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "dfgasfdgasfgasdf",
    "adress":"casa da mãe joana",
    "phone":11123456789,
    "email": "asdasdasda@gmail.com",
    "birth_date":"1990-01-01",
    "login":"asdasdasda",
    "password": "abc123",
    "profile_pic":"bananinha"
}

##
# @name login
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "asdasdasda@gmail.com",
    "password": "abc123"
}


